### ISSUE TITLE
ansible-playbook with --vault-password-file fails

### ISSUE THREAD

**Issue by paikov** [bigpandaio/ansible-workshop#2]
In step 8, this command:
ansible-playbook ./deploy.yml --vault-password-file=.ansible-vault-pass --tags web
... produces this error:
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode'

Using Ansible 2.0.

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
